# Generated by Django 5.0.2 on 2024-03-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('screen', models.CharField(max_length=100)),
            ],
        ),
    ]
